general:
  working_dir: ./
  logging_level: INFO


prepare:
  general:
    dataset_path: data/dataset.json
    test_size: 0.2
    processed_dataset_path: data/processed_data
    n_jobs: 8
  image:
    size: 256
    face_score_threshold: 0.75
    face_area_threshold: 2500

train:
  init:
    train_dataset_path: data/imdb_wiki/train.json  # путь к json-файлу с описанием датасета для обучения
    test_dataset_path: data/imdb_wiki/test.json  # путь к json-файлу с описанием датасета для валидации во время обучения
    model: inception_resnet_v1 #  варианты: 1) inception_resnet_v1     2) resnet_v2_50
    pretrained_model_folder_or_file: models/pretrained_models # файл модели или папка с файлами для загрузки с диска
    save_frequency: 5  # частота сохранения моделей
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 1
  batch_size: 16  # 30 максимум для GeForce 1060
  keep_prob: 0.8
  cuda: True




